apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedula-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: schedula-backend
          ports:
            - containerPort: 5000